export const holidays = [
  { event: "New Year Day", date: "1st January", day: "Wednesday", off: "01" },
  { event: "Makar Sankranti", date: "14th January", day: "Tuesday", off: "01" },
  { event: "Netaji Birthday", date: "23rd January", day: "Thursday", off: "01" },
  { event: "Saraswati Puja", date: "3rd February", day: "Monday", off: "01" },
  { event: "Shab-e-Barat", date: "14th February", day: "Friday", off: "01" },
  { event: "Dol (Holi)", date: "14th March", day: "Friday", off: "02" },
  { event: "Id-ul-Fitr", date: "31st March", day: "Monday", off: "01" },
  { event: "Bengali New Year", date: "15th April", day: "Tuesday", off: "01" },
  { event: "May Day", date: "1st May", day: "Thursday", off: "01" },
  { event: "Rabindra Jayanti", date: "8th May", day: "Thursday", off: "01" },
  { event: "Summer Vacation", date: "Will be notified later", day: "–", off: "–" },
  { event: "Bakrid", date: "7th June", day: "Saturday", off: "01" },
  { event: "Rathayatra", date: "22nd June", day: "Saturday", off: "01" },
  { event: "Muharram", date: "6th July", day: "Sunday", off: "01" },
  { event: "Raksha Bandhan", date: "9th August", day: "Saturday", off: "01" },
  { event: "Independence Day", date: "15th August", day: "Friday", off: "01" },
  { event: "Janmashtami", date: "16th August", day: "Saturday", off: "01" },
  { event: "Vishwakarma Puja", date: "17th September", day: "Wednesday", off: "01" },
  { event: "Durga Puja Holiday", date: "28th Sept – 7th Oct", day: "Saturday – Tuesday", off: "10" },
  { event: "Kali Puja / Bhai Phota", date: "20th – 23rd October", day: "Monday – Thursday", off: "01" },
  { event: "Guru Nanak Birthday", date: "15th November", day: "Saturday", off: "01" },
  { event: "X-Mas Day", date: "25th December", day: "Thursday", off: "01" },
  { event: "Head Master’s Consideration", date: "–", day: "–", off: "2 Days Extra" },
];